# This is a basic workflow to help you get started with Actions

name: CI-linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    #branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    #branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Setup ubuntu'
        run: sudo apt-get install -y libmpfr-devel libmpc-devel libisl-devel

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - run: git config --global core.autocrlf input
      - name: '🧰 Checkout'
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
#      - name: Run a one-line script
#        run:  gcc -dumpmachine

#      - name: Run a one-line script
#        run:  pacman -Q

#      - name: Run a one-line script
#        run:  exit 1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Runs a single command using the runners shell
      - name: Run a script
        run: bash ./build-devkit.sh
